### ISSUE TITLE
Implement a method for saving courses

### ISSUE THREAD

**Issue by KoehlerTill** [klaus94/TimeTable#11]
- [x] Technologie suchen 
- [x] Kurse speichern
- [x] Kurse laden
- [x] Auswahlmenu für das Speichern und Laden, an welchem Ort die entsprechende Datei liegt

**Comment by klaus94** [comment]
Ich hab da mal was kleines geschrieben. Die Kurse werden jetzt in einer xml-Datei gespeichert. Das Auslesen verursacht noch Fehler.
